### ISSUE TITLE
Can't fetch tickets from DB

### ISSUE THREAD

**Issue by NirAlon** [DevShashi1993/helpdesk-ticketing-sytem#1]
Hi,
First I want to thank you for your Helpdesk_Ticketing_System project.
I'm dealing with an issue in your project that I can't show on react results from DB
For example I would like to use the function "getTickets()" in "ticketActions.js", the server side is working well and with Postman I'm receiving the data. 
But on the client side, I haven't figure out yet how and where to implement the function "getTickets()" and show results.

For now at the client side on "TicketsView/Tickets.js" you implement "rows" with static data, and I want to load "rows" with "getTickets()" results. 

Thanks.

**Comment by DevShashi1993** [comment]
@NirAlon Thanks! for the feedback and it feels great to hear that my project help you. 

As this project is still in progress and due to my hectic workload I was not able to work on that fetching ticket data issue. In fact, my next task was to implement that feature only (i.e fetching ticket data from the Database). I am still figuring out which table to use to display all the tickets as the table component provided by Material-UI is not up to the mark, it lacks features like group by columns, import-export to Docx/Pdf, Search, Column with Edit/Delete Action Buttons, Custom Styling of the rows on particular conditions, etc. 

However, by end of this week, the reported feature will be completed. 
Happy Coding !!!

**Comment by NirAlon** [comment]
That's great news!

Btw it was not that easy to run your project as following to the README file: 
First need to run "yarn start" on client side and also on server side, it wasn't that obvious. 
I had to install each dependency on your project (yarn add ...) because somehow the project.json wasn't include all the dependencies.
I had to made few changes on the queries to the DB since it is not standing correct with the tables&columns on the loaded *.sql

I'm looking forward for the next commit!
Happy Coding !!

**Comment by DevShashi1993** [comment]
> That's great news!
> 
> Btw it was not that easy to run your project as following to the README file:
> First need to run "yarn start" on client side and also on server side, it wasn't that obvious.
> I had to install each dependency on your project (yarn add ...) because somehow the project.json wasn't include all the dependencies.
> I had to made few changes on the queries to the DB since it is not standing correct with the tables&columns on the loaded *.sql
> 
> I'm looking forward for the next commit!
> Happy Coding !!

Thanks again for the feedback. 

I will surely improve my README part, with the detailed steps and will also look into the missing dependencies in the package.json file and also the schema.sql if any changes were not committed.
As far as making the client-side and server-side separate is concerned, this is something I prefer to make.....BTW I will add a new task to my todo-list to build some shell script, that can auto-install the dependencies in the respective folders with a single batch command.

**Comment by DevShashi1993** [comment]
Closing this issue, as this project now supports fetching all the created tickets data from the database and populating it inside the table. Also, the delete ticket feature and delete all tickets feature have been added with the improved README.

Happy Coding !!
